"""Curated interview question banks, per skill.

Each skill has 60 questions across four levels — beginner (20), intermediate
(15), advanced (15), and practical (15→10) — so a candidate closing a gap can
prepare, not just read docs. Questions are hand-curated (not generated) so they
are stable and interview-realistic; a skill with no bank returns nothing rather
than a fabricated list. Extend `_BANKS` to cover more skills.
"""

from typing import Any, Dict, List, Optional

# (key, display label), in the order they are shown.
LEVELS = [
    ("beginner", "Beginner"),
    ("intermediate", "Intermediate"),
    ("advanced", "Advanced"),
    ("practical", "Practical"),
]

# skill (canonical name) -> {level: [question, ...]}
_BANKS: Dict[str, Dict[str, List[str]]] = {
    "LLM": {
        "beginner": [
            "What is a large language model (LLM)?",
            "What does 'autoregressive' mean in the context of LLMs?",
            "What is a token, and how is text broken into tokens?",
            "What is the difference between a word and a token?",
            "What is a context window, and why does it matter?",
            "What is the difference between pre-training and fine-tuning?",
            "What is a prompt, and what is prompt engineering?",
            "What is the difference between zero-shot, one-shot, and few-shot prompting?",
            "What does the 'temperature' setting control during generation?",
            "What are top-k and top-p (nucleus) sampling?",
            "What is a hallucination in an LLM, and why does it happen?",
            "Describe the transformer architecture at a high level.",
            "What is the role of the attention mechanism?",
            "What is an embedding, and how do LLMs use them?",
            "What is the difference between an encoder, a decoder, and an encoder-decoder model?",
            "What do parameters mean in an LLM, and what does a size like '7B' indicate?",
            "What is the difference between a system prompt and a user prompt?",
            "How do GPT-style models differ from BERT-style models?",
            "What are stop sequences and the max-tokens limit in generation?",
            "Why can't an LLM answer questions about events after its training cutoff?",
        ],
        "intermediate": [
            "Explain self-attention and how query, key, and value vectors are used.",
            "What is multi-head attention and why is it useful?",
            "What is positional encoding and why do transformers need it?",
            "Compare RLHF with plain supervised fine-tuning for aligning a model.",
            "What is instruction tuning?",
            "Why does attention cost scale quadratically with sequence length?",
            "What is the difference between greedy decoding and beam search?",
            "How does the choice of tokenizer (e.g., BPE) affect performance and cost?",
            "What is catastrophic forgetting during fine-tuning, and how do you mitigate it?",
            "What is the difference between fine-tuning and in-context learning?",
            "How do you evaluate an LLM's output quality, automatically and with humans?",
            "What is a mixture-of-experts (MoE) model?",
            "What are scaling laws and what do they predict?",
            "How does the KV cache speed up autoregressive generation?",
            "What are guardrails and why are they needed in production LLM apps?",
        ],
        "advanced": [
            "Explain LoRA and how it reduces the cost of fine-tuning.",
            "What is quantization (INT8/INT4) and what are its trade-offs?",
            "Walk through RLHF end to end, including the reward model and PPO.",
            "What is Direct Preference Optimization (DPO) and how does it differ from RLHF?",
            "Explain FlashAttention and why it improves throughput.",
            "What is speculative decoding and when does it help?",
            "How can you extend a model's context window (e.g., RoPE scaling, ALiBi)?",
            "Compare dense attention with sparse attention approaches.",
            "How do you defend an LLM application against prompt injection?",
            "Explain grouped-query attention (GQA) and multi-query attention (MQA).",
            "How would you serve a large model efficiently (continuous batching, paged attention)?",
            "What is model distillation and when would you use it?",
            "How do you measure and reduce toxicity or bias in an LLM?",
            "What are the trade-offs of a larger context window versus retrieval?",
            "How do you fine-tune on proprietary data without leaking it into outputs?",
        ],
        "practical": [
            "Design a customer-support assistant that must not invent policy details.",
            "Your LLM feature is slow and expensive at scale — how do you cut latency and cost?",
            "A prompt works in testing but fails on edge cases in production — how do you debug it?",
            "Build an evaluation harness to objectively compare two prompt versions.",
            "Users report the model leaking other users' data — how do you investigate and fix it?",
            "Choose between fine-tuning and RAG for a domain-specific Q&A bot, and justify it.",
            "Implement streaming responses and explain the UX and backend implications.",
            "Reduce hallucinations for a factual task without retraining the model.",
            "Handle a 100k-token document that exceeds the context window.",
            "Set up guardrails that block unsafe requests while minimizing false positives.",
        ],
    },
    "RAG": {
        "beginner": [
            "What is Retrieval-Augmented Generation (RAG)?",
            "Why use RAG instead of relying only on the model's parametric knowledge?",
            "What are the main components of a RAG pipeline?",
            "What is an embedding in the context of RAG?",
            "What is a vector database and why is it used in RAG?",
            "What is chunking and why is it necessary?",
            "What is the difference between semantic search and keyword search?",
            "What is cosine similarity and how is it used to find relevant chunks?",
            "What is the difference between the retrieval step and the generation step?",
            "What is the 'context' that gets passed to the LLM in RAG?",
            "Why can RAG reduce hallucinations?",
            "What is top-k retrieval?",
            "How is an embedding model different from an LLM?",
            "What metadata might you store alongside each chunk?",
            "What is the role of a re-ranker?",
            "What is the difference between dense and sparse retrieval?",
            "Why does chunk size affect retrieval quality?",
            "What is a knowledge base in a RAG system?",
            "What happens if the retriever returns irrelevant chunks?",
            "How does RAG serve information newer than the model's training cutoff?",
        ],
        "intermediate": [
            "How do you choose chunk size and overlap, and what are the trade-offs?",
            "Compare dense retrieval with BM25; when would you use hybrid search?",
            "How does a cross-encoder re-ranker differ from bi-encoder retrieval?",
            "What is Maximal Marginal Relevance (MMR) and why use it?",
            "How do you evaluate a RAG system's retrieval and generation separately?",
            "What is the 'lost in the middle' problem and how do you mitigate it?",
            "How do you handle multi-hop questions in RAG?",
            "What is query expansion or query rewriting?",
            "How do you decide how many chunks (k) to retrieve?",
            "What are common failure modes of RAG and their causes?",
            "How do you keep the vector index fresh as source documents change?",
            "What is HyDE (Hypothetical Document Embeddings)?",
            "How do you attribute an answer to its sources (citations)?",
            "What indexing strategies do vector databases use (HNSW, IVF)?",
            "How do you handle documents written in multiple languages?",
        ],
        "advanced": [
            "Design a RAG system over millions of documents — architecture and trade-offs.",
            "How do you reduce hallucination when the retrieved context is insufficient?",
            "Compare fine-tuning, RAG, and long-context prompting for domain knowledge.",
            "How would you implement agentic or iterative retrieval?",
            "How do you evaluate faithfulness/groundedness automatically?",
            "How do you isolate tenants so a RAG system never leaks data across them?",
            "What are the trade-offs of HNSW parameters (M, efConstruction, efSearch)?",
            "How do you combine structured (SQL) and unstructured retrieval?",
            "How do you cache and reduce cost in a high-traffic RAG service?",
            "How do you handle conflicting information across retrieved sources?",
            "What is parent-document (contextual) retrieval?",
            "How do you chunk code or tables differently from prose?",
            "How do you measure and trade off retrieval recall versus precision?",
            "How do you A/B test embedding models safely in production?",
            "How do you handle documents that exceed the context window even after retrieval?",
        ],
        "practical": [
            "Answers cite the wrong document — how do you debug the retrieval step?",
            "Build a RAG chatbot over internal wikis with per-user access control.",
            "Retrieval is poor for acronym-heavy queries — how do you fix it?",
            "Your vector database is too slow at scale — how do you optimize it?",
            "Design an evaluation set and metrics so you can ship RAG changes confidently.",
            "The model ignores the provided context — how do you improve grounding?",
            "Keep answers current for documents that update several times a day.",
            "Cost is high from over-retrieving tokens per query — how do you reduce it?",
            "Add clickable source citations to every answer — design it.",
            "Choose between hybrid search and pure vector search for a legal-docs bot.",
        ],
    },
    "NLP": {
        "beginner": [
            "What is Natural Language Processing (NLP)?",
            "What is tokenization?",
            "What is the difference between stemming and lemmatization?",
            "What are stop words and when do you remove them?",
            "What is a bag-of-words model?",
            "What is TF-IDF?",
            "What is a word embedding (e.g., Word2Vec, GloVe)?",
            "What is Named Entity Recognition (NER)?",
            "What is part-of-speech (POS) tagging?",
            "What is sentiment analysis?",
            "What is text classification?",
            "What is an n-gram?",
            "What is the difference between syntax and semantics?",
            "What is a corpus?",
            "What is one-hot encoding of words, and what is its main limitation?",
            "What is language modeling?",
            "What is the difference between a token and a lemma?",
            "What is text normalization?",
            "How do you read a confusion matrix for a text classifier?",
            "What is the difference between precision and recall for an NLP task?",
        ],
        "intermediate": [
            "How do contextual embeddings (BERT) differ from static ones (Word2Vec)?",
            "Explain the attention mechanism as used in transformers for NLP.",
            "What is subword tokenization (BPE, WordPiece) and why use it?",
            "How does BERT's masked language modeling objective work?",
            "What is transfer learning in NLP?",
            "What is sequence-to-sequence modeling?",
            "How do you handle class imbalance in text classification?",
            "What is the difference between extractive and abstractive summarization?",
            "What metrics are used for translation and summarization (BLEU, ROUGE)?",
            "What is coreference resolution?",
            "How do you deal with out-of-vocabulary words?",
            "What is perplexity for a language model?",
            "How does fine-tuning a pre-trained model for a downstream task work?",
            "How do you handle multilingual text?",
            "What is the difference between generative and discriminative NLP models?",
        ],
        "advanced": [
            "Build a production NER system for a new domain with little labeled data — how?",
            "Explain how transformers replaced RNNs/LSTMs for sequence tasks.",
            "How do you evaluate a text-generation model beyond BLEU/ROUGE?",
            "How do you detect and mitigate bias in NLP models?",
            "How would you compress a transformer for on-device inference?",
            "What are the challenges of long-document understanding?",
            "How do you do entity linking at scale?",
            "How do you adapt a sentiment model to a new domain?",
            "What is weak supervision or data programming for labeling?",
            "How do you handle sarcasm and negation in sentiment analysis?",
            "How do you make a text classifier robust to adversarial inputs?",
            "Explain contrastive learning for sentence embeddings (e.g., SBERT).",
            "How do you measure and reduce toxicity in generated text?",
            "How would you approach NLP for a low-resource language?",
            "How do you calibrate the confidence scores of an NLP classifier?",
        ],
        "practical": [
            "Build a support-ticket classifier with only 200 labeled examples.",
            "Your sentiment model fails on negation ('not good') — how do you fix it?",
            "Design a pipeline to extract structured fields from resumes.",
            "Deduplicate near-identical documents at scale — how?",
            "A classifier is 95% accurate but useless — what's wrong and how do you diagnose it?",
            "Build semantic search over a knowledge base — components and choices.",
            "Reduce the inference latency of a BERT classifier in production.",
            "Handle a language your model was never trained on.",
            "Build an evaluation set for a summarizer and choose the metrics.",
            "Detect PII in free text before storing it.",
        ],
    },
    "Machine Learning": {
        "beginner": [
            "What is the difference between supervised, unsupervised, and reinforcement learning?",
            "What is the difference between classification and regression?",
            "What are overfitting and underfitting?",
            "What is the bias-variance trade-off?",
            "What are training, validation, and test splits for?",
            "What is cross-validation?",
            "What is a feature, and what is feature engineering?",
            "What is the difference between normalization and standardization?",
            "What are precision, recall, and F1-score?",
            "What is a confusion matrix?",
            "What is gradient descent?",
            "What is a loss function?",
            "What is regularization, and how do L1 and L2 differ?",
            "What is the difference between parameters and hyperparameters?",
            "What is one-hot encoding?",
            "What is the curse of dimensionality?",
            "How does a decision tree make predictions?",
            "What is ensemble learning (bagging vs boosting)?",
            "What is the difference between accuracy and AUC-ROC?",
            "What is data leakage?",
        ],
        "intermediate": [
            "How does a random forest reduce overfitting compared to a single tree?",
            "Explain how gradient boosting (e.g., XGBoost) works.",
            "How do you handle an imbalanced dataset?",
            "What is the difference between bagging and boosting?",
            "How do you choose evaluation metrics for imbalanced classification?",
            "What is k-means and how do you choose k?",
            "What is PCA and when do you use it?",
            "How do L1 and L2 regularization differ in their effect on weights?",
            "How does a support vector machine work (margin, kernel trick)?",
            "What is early stopping?",
            "How do you tune hyperparameters (grid, random, Bayesian search)?",
            "What is the difference between generative and discriminative models?",
            "How do you detect and handle multicollinearity?",
            "What is feature importance, and how can it mislead you?",
            "What is the difference between online and batch learning?",
        ],
        "advanced": [
            "A model does well offline but poorly in production — how do you debug it?",
            "What is concept drift and how do you detect and handle it?",
            "What cross-validation strategy is right for time-series data, and why?",
            "How do you build a reproducible ML pipeline?",
            "How do you calibrate a classifier's predicted probabilities?",
            "Explain SHAP values and model explainability.",
            "How do you design an A/B test to evaluate a new model?",
            "How do you handle missing data beyond simple imputation?",
            "How do you detect label noise and reason about its impact?",
            "How do you decide between a simpler and a more complex model for production?",
            "What is the difference between MLE and MAP estimation?",
            "How do you monitor a deployed model over time?",
            "How do you address fairness and bias in a model's predictions?",
            "How would you approach feature selection at scale?",
            "What is training/serving skew and how do you prevent it?",
        ],
        "practical": [
            "Your model's accuracy dropped in production last week — how do you investigate?",
            "Build a churn-prediction model — walk through the full pipeline.",
            "You have 1M rows but only 500 positives — how do you approach it?",
            "Design a system to retrain and deploy a model safely and automatically.",
            "A stakeholder wants an explanation for every prediction — how do you deliver it?",
            "Reduce training time on a large dataset — practical techniques.",
            "Your features leak the target — how do you detect and prevent it?",
            "Choose the metrics for a fraud-detection model and justify them.",
            "Handle a dataset where 30% of a key feature is missing.",
            "Deploy a model under strict latency requirements — design choices.",
        ],
    },
    "Docker": {
        "beginner": [
            "What is Docker and what problem does it solve?",
            "What is the difference between a container and a virtual machine?",
            "What is a Docker image?",
            "What is a Dockerfile?",
            "What is the difference between an image and a container?",
            "What does `docker build` do?",
            "What does `docker run` do?",
            "What is Docker Hub?",
            "What is a container registry?",
            "What is the difference between COPY and ADD in a Dockerfile?",
            "What is the difference between CMD and ENTRYPOINT?",
            "What are image layers?",
            "What is a base image?",
            "How do you expose a port from a container?",
            "What is a volume and why is it used?",
            "What is the difference between a bind mount and a volume?",
            "What does `docker ps` show?",
            "How do you view a container's logs?",
            "What is the purpose of a .dockerignore file?",
            "What is the difference between `docker stop` and `docker kill`?",
        ],
        "intermediate": [
            "How does Docker layer caching work and how do you optimize it?",
            "What is a multi-stage build and why use it?",
            "How do you reduce a Docker image's size?",
            "What is the difference between EXPOSE and publishing a port with -p?",
            "How do containers communicate over a Docker network?",
            "What are the default Docker network drivers (bridge, host, none)?",
            "How do you pass configuration and secrets to a container?",
            "What is Docker Compose and when do you use it?",
            "What is the difference between ARG and ENV?",
            "How do you run a container as a non-root user, and why?",
            "What is a health check in Docker?",
            "How does a container's filesystem persist (or not) data?",
            "What happens to a container when its main process exits?",
            "How do you tag and version images for a release?",
            "What is the difference between `docker exec` and `docker attach`?",
        ],
        "advanced": [
            "How would you secure a Docker image and container in production?",
            "Explain the container isolation primitives (namespaces, cgroups).",
            "How do you scan images for vulnerabilities in CI?",
            "How do you minimize the attack surface of a base image (distroless, scratch)?",
            "How do you handle secrets so they never end up in image layers?",
            "What are the trade-offs of running Docker-in-Docker?",
            "How do you debug a container that keeps restarting?",
            "How does BuildKit improve builds?",
            "How do you set CPU/memory limits and why do they matter?",
            "How do you build multi-architecture images?",
            "How do you reduce Docker build time in a CI pipeline?",
            "What are the risks of the 'latest' tag in production?",
            "How do you persist and back up stateful container data?",
            "How does the OverlayFS storage driver work?",
            "How do you sign and verify image provenance?",
        ],
        "practical": [
            "Your image is 1.5GB — how do you shrink it?",
            "A container works locally but fails in CI — how do you debug it?",
            "Write a Dockerfile for a Python or Node app optimized for caching and size.",
            "A container can't reach a database container — how do you diagnose the network?",
            "Secrets are showing up in `docker history` — how do you fix it?",
            "Set up Compose for an app with a web service, a database, and a cache.",
            "Your build re-downloads dependencies every time — how do you cache them?",
            "Handle graceful shutdown of a container on SIGTERM.",
            "Reduce a slow 10-minute CI Docker build to under 3 minutes.",
            "Run the same image in dev and prod with different configuration — how?",
        ],
    },
    "Kubernetes": {
        "beginner": [
            "What is Kubernetes and what problem does it solve?",
            "What is a Pod?",
            "What is the difference between a node and a cluster?",
            "What is a Deployment?",
            "What is a Service, and what are its types (ClusterIP, NodePort, LoadBalancer)?",
            "What is a ReplicaSet?",
            "What is kubectl?",
            "What is a namespace?",
            "What is the difference between a container and a Pod?",
            "What are labels and selectors?",
            "What is a ConfigMap?",
            "What is a Secret?",
            "What is the difference between a Deployment and a StatefulSet?",
            "What is an Ingress?",
            "What is the control plane?",
            "What is the kubelet?",
            "What is a manifest (YAML) file?",
            "What does `kubectl apply` do?",
            "What is a rolling update?",
            "What does 'desired state vs current state' mean in Kubernetes?",
        ],
        "intermediate": [
            "How does a Deployment perform a rolling update, and how do you roll back?",
            "What are liveness, readiness, and startup probes?",
            "How do resource requests and limits affect scheduling?",
            "How does the Horizontal Pod Autoscaler work?",
            "What is a DaemonSet and when do you use it?",
            "How does service discovery work in Kubernetes?",
            "What is the practical difference between a ConfigMap and a Secret?",
            "How do you persist data with PersistentVolumes and PersistentVolumeClaims?",
            "What are taints and tolerations?",
            "What is node affinity and anti-affinity?",
            "How does the scheduler decide where to place a Pod?",
            "What is the difference between a Job and a CronJob?",
            "How do you expose an app externally with a Service and Ingress?",
            "What happens when a node fails?",
            "What is the difference between `kubectl apply` and `kubectl create`?",
        ],
        "advanced": [
            "How would you design a highly available, multi-zone cluster?",
            "Explain how RBAC works and how you'd scope permissions.",
            "How do you implement zero-downtime deployments?",
            "What are network policies and how do they secure traffic?",
            "How do you manage secrets securely (sealed secrets, external secrets)?",
            "How does the HPA interact with resource requests and metrics?",
            "How would you debug a Pod stuck in CrashLoopBackOff or Pending?",
            "What guarantee does a StatefulSet give, and when is it essential?",
            "How do you do canary or blue-green deployments in Kubernetes?",
            "How do operators and custom resources (CRDs) extend Kubernetes?",
            "How do you handle cluster upgrades safely?",
            "How does the pod networking model (CNI) work?",
            "How and why do you set Pod Disruption Budgets?",
            "How would you reduce cluster cost while keeping reliability?",
            "How do you observe and troubleshoot a slow service (metrics, tracing)?",
        ],
        "practical": [
            "A Pod is stuck in Pending — how do you diagnose it?",
            "Your rolling update took the service down — what went wrong and how do you prevent it?",
            "Write manifests for a stateless web app with autoscaling and health checks.",
            "A service intermittently returns 503 — how do you investigate?",
            "Roll out a risky change to 5% of traffic first — how?",
            "A Pod is OOMKilled repeatedly — how do you fix it?",
            "Secrets are committed in plain YAML — how do you remediate?",
            "Set up ingress with TLS for two services.",
            "One noisy app is starving others — how do you isolate it?",
            "Migrate a stateful database onto Kubernetes safely.",
        ],
    },
    "Redis": {
        "beginner": [
            "What is Redis?",
            "Why is Redis fast?",
            "What data structures does Redis support?",
            "What is a key in Redis?",
            "How does Redis differ from a relational database?",
            "What is caching and why use Redis for it?",
            "What is TTL (time to live) on a key?",
            "What is the difference between SET and SETEX?",
            "What are Redis Strings, Lists, Sets, Hashes, and Sorted Sets?",
            "Is Redis single-threaded, and what does that imply?",
            "What do GET and SET do?",
            "What is INCR used for?",
            "When would you use a Redis Hash?",
            "What is a Sorted Set (ZSET) used for?",
            "What does EXPIRE do?",
            "What is the difference between in-memory and on-disk storage?",
            "What is a cache hit versus a cache miss?",
            "What does DEL do?",
            "How do you check whether a key exists?",
            "What is Redis commonly used for besides caching?",
        ],
        "intermediate": [
            "What persistence options does Redis have (RDB vs AOF)?",
            "What are the trade-offs of RDB versus AOF?",
            "What is a cache eviction policy (LRU, LFU, etc.)?",
            "What do the different maxmemory-policy options do?",
            "How does Redis Pub/Sub work?",
            "What is pipelining and why does it help?",
            "What is a Redis transaction (MULTI/EXEC)?",
            "How do you implement a distributed lock with Redis?",
            "What is the cache-aside pattern?",
            "What are the write-through and write-behind caching strategies?",
            "How do lazy and active key expiration work?",
            "How do you avoid a cache stampede (thundering herd)?",
            "What is Redis replication (master/replica)?",
            "How do you use Redis as a rate limiter?",
            "What is the difference between Redis and Memcached?",
        ],
        "advanced": [
            "How does Redis Cluster shard data, and what are the trade-offs?",
            "How do you achieve high availability with Redis Sentinel?",
            "What is a hot-key problem and how do you mitigate it?",
            "How do you handle cache invalidation reliably?",
            "What are the consistency guarantees of Redis replication?",
            "How do Lua scripts help with atomicity?",
            "How do you size and monitor Redis memory?",
            "What happens during a failover, and how do clients handle it?",
            "How do you prevent cache penetration (repeatedly querying missing keys)?",
            "How do you reshard a Redis Cluster with minimal downtime?",
            "Why is `KEYS` dangerous in production, and what is the alternative?",
            "How do you design keys and TTLs for a large-scale cache?",
            "How does Redis perform with very large values or collections?",
            "How would you use Redis Streams for event processing?",
            "How do you secure a Redis deployment (auth, TLS, network)?",
        ],
        "practical": [
            "Your cache hit rate is low — how do you investigate and improve it?",
            "A cache stampede takes down the DB after a key expires — how do you fix it?",
            "Design a rate limiter allowing 100 requests/min per user with Redis.",
            "Redis memory keeps growing until OOM — how do you diagnose it?",
            "Implement a leaderboard — which structure and commands?",
            "A `KEYS *` froze the server in production — what do you use instead?",
            "Design cache invalidation for frequently updated user profiles.",
            "Handle failover so the app doesn't error during a master switch.",
            "Store session data with expiry — design the keys.",
            "One hot key is overloading a single shard — how do you spread the load?",
        ],
    },
    "GraphQL": {
        "beginner": [
            "What is GraphQL?",
            "How does GraphQL differ from REST?",
            "What is a schema in GraphQL?",
            "What is a query?",
            "What is a mutation?",
            "What is a subscription?",
            "What is a resolver?",
            "What are scalar types in GraphQL?",
            "What are types and fields?",
            "What is the difference between a query and a mutation?",
            "What are over-fetching and under-fetching, and how does GraphQL address them?",
            "Why does GraphQL typically use a single endpoint?",
            "What are arguments on a GraphQL field?",
            "What is an input type?",
            "What does a non-null (!) type mean?",
            "What does a list type ([Type]) mean?",
            "What is introspection?",
            "What is a fragment?",
            "What is an alias in a query?",
            "What tools are used to explore a GraphQL API (e.g., GraphiQL)?",
        ],
        "intermediate": [
            "What is the N+1 problem in GraphQL and how do you solve it (DataLoader)?",
            "How does GraphQL handle errors compared to REST status codes?",
            "What are interfaces and unions in GraphQL?",
            "What is schema stitching or federation?",
            "How do you implement pagination (offset vs cursor/Relay)?",
            "How do you handle authentication and authorization in GraphQL?",
            "What is a directive? Give an example.",
            "How does caching differ between GraphQL and REST?",
            "How is data passed through the resolver chain (parent/args/context)?",
            "How do you version a GraphQL API?",
            "What is a persisted query?",
            "How do subscriptions work under the hood (WebSockets)?",
            "How do you validate and sanitize inputs?",
            "What is the difference between a query variable and an inline argument?",
            "How do you structure resolvers for a large schema?",
        ],
        "advanced": [
            "How do you prevent expensive or malicious queries (depth/complexity limiting)?",
            "How does Apollo Federation compose multiple services?",
            "How do you handle caching at scale (client, CDN, server)?",
            "How do you secure a GraphQL API against introspection abuse?",
            "How do you implement fine-grained, per-field authorization?",
            "How do you monitor and trace resolver performance?",
            "What are the trade-offs of GraphQL versus REST for a public API?",
            "How do you handle file uploads in GraphQL?",
            "How do you design a schema for evolvability (deprecation)?",
            "How do you batch and cache with DataLoader across a request?",
            "How do you rate-limit a GraphQL endpoint?",
            "How do you test a GraphQL API effectively?",
            "How do you handle real-time at scale with subscriptions?",
            "How do you avoid tight coupling between the schema and the database?",
            "How do you migrate a REST API to GraphQL incrementally?",
        ],
        "practical": [
            "A query is slow due to N+1 — how do you fix it?",
            "Design a schema for a blog with users, posts, and comments.",
            "Clients send deeply nested queries that overload the server — how do you protect it?",
            "Add cursor-based pagination to a posts query.",
            "Implement per-field authorization so only owners see private fields.",
            "A mutation partially fails — how do you report errors to the client?",
            "Cache a public GraphQL query at the CDN — how?",
            "Add real-time comment updates via subscriptions.",
            "Federate a users service and an orders service into one graph.",
            "Deprecate a field without breaking existing clients.",
        ],
    },
    "CI/CD": {
        "beginner": [
            "What is CI/CD?",
            "What is Continuous Integration?",
            "What is the difference between Continuous Delivery and Continuous Deployment?",
            "What is a pipeline?",
            "What is a build stage?",
            "What triggers a CI pipeline?",
            "What is a runner or agent?",
            "What is a build artifact?",
            "Why do you run tests in CI?",
            "What is a pull-request check?",
            "What is the difference between a job and a stage?",
            "What is a deployment environment (dev/staging/prod)?",
            "What role does version control play in CI/CD?",
            "What is a rollback?",
            "What is a pipeline secret or environment variable?",
            "What is a status check on a commit?",
            "What is caching in CI and why use it?",
            "What is a build matrix?",
            "What does a 'green build' mean?",
            "What is the core difference between CI and CD?",
        ],
        "intermediate": [
            "How do you keep CI pipelines fast?",
            "What is a blue-green deployment?",
            "What is a canary deployment?",
            "How do you manage secrets in a pipeline securely?",
            "What is Infrastructure as Code and how does it fit CI/CD?",
            "How do you gate a deployment on tests or approvals?",
            "What is artifact versioning and promotion across environments?",
            "How do you handle database migrations during a deploy?",
            "What is a feature flag and how does it support continuous deployment?",
            "How do you parallelize tests in CI?",
            "How does CI differ for a monorepo versus multiple repos?",
            "How do you cache dependencies between runs?",
            "What is a manual approval gate and when do you use one?",
            "How do you run integration tests that need services (DB, cache)?",
            "What is the difference between push-based and pull-based (GitOps) deployment?",
        ],
        "advanced": [
            "How would you design a zero-downtime deployment pipeline?",
            "How do you implement automated rollback on failed health checks?",
            "How do you secure the software supply chain (SBOM, signing, provenance)?",
            "How do you scan for vulnerabilities and secrets in CI?",
            "What is GitOps and how does it work (e.g., Argo CD)?",
            "How do you handle multi-region or multi-cluster deployments?",
            "How do you stop flaky tests from undermining the pipeline?",
            "How do you implement progressive delivery (canary with metric-based promotion)?",
            "How do you keep environment parity to avoid 'works on staging'?",
            "How do you structure pipelines for a large monorepo (affected-only builds)?",
            "How do you enforce policy (e.g., OPA) in a pipeline?",
            "How do you audit and trace what was deployed and by whom?",
            "How do you run long migrations without downtime?",
            "How do you test infrastructure changes safely?",
            "How do you balance deployment speed against safety controls?",
        ],
        "practical": [
            "Your pipeline takes 40 minutes — how do you speed it up?",
            "A deploy broke production — design an automatic rollback.",
            "Secrets leaked in build logs — how do you remediate and prevent it?",
            "Set up a pipeline: lint, test, build image, deploy to staging, gate to prod.",
            "Flaky tests keep failing the build — how do you stabilize them?",
            "Roll out a change to 5% of users and auto-promote on healthy metrics.",
            "A schema migration must ship with zero downtime — how?",
            "Behavior differs between staging and prod — how do you fix parity?",
            "Cache dependencies so builds don't re-download every time.",
            "Add security scanning that fails the build on critical vulnerabilities.",
        ],
    },
}


def has_questions(skill: str) -> bool:
    return skill in _BANKS


def question_counts(skill: str) -> Optional[Dict[str, int]]:
    """Per-level and total counts for a skill, or None if it has no bank."""
    bank = _BANKS.get(skill)
    if not bank:
        return None
    counts = {level: len(bank.get(level, [])) for level, _ in LEVELS}
    counts["total"] = sum(counts.values())
    return counts


def questions_for(skill: str) -> Optional[Dict[str, Any]]:
    """The full question bank for a skill, grouped by level, or None."""
    bank = _BANKS.get(skill)
    if not bank:
        return None
    levels = [
        {
            "level": level,
            "label": label,
            "count": len(bank.get(level, [])),
            "questions": list(bank.get(level, [])),
        }
        for level, label in LEVELS
    ]
    return {
        "skill": skill,
        "total": sum(item["count"] for item in levels),
        "levels": levels,
    }


def bank_summary(skills: List[str]) -> Dict[str, Dict[str, int]]:
    """Counts for each of `skills` that has a bank, for a roadmap overview."""
    summary: Dict[str, Dict[str, int]] = {}
    for skill in skills:
        counts = question_counts(skill)
        if counts is not None and skill not in summary:
            summary[skill] = counts
    return summary
