"""Initial migration

Revision ID: 92f9b5ffe7fc
Revises: 
Create Date: 2026-07-28 00:33:41.099097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f9b5ffe7fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('dashboard_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_snapshots_created_at'), 'dashboard_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboard_snapshots_id'), 'dashboard_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_snapshots_is_deleted'), 'dashboard_snapshots', ['is_deleted'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_created_at'), 'job_descriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_is_deleted'), 'job_descriptions', ['is_deleted'], unique=False)
    op.create_table('learning_paths',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_data', sa.JSON(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_created_at'), 'learning_paths', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_learning_paths_is_deleted'), 'learning_paths', ['is_deleted'], unique=False)
    op.create_table('resumes',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_is_deleted'), 'resumes', ['is_deleted'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('priority_skills', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_created_at'), 'skill_gaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_gaps_id'), 'skill_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_is_deleted'), 'skill_gaps', ['is_deleted'], unique=False)
    op.create_table('alignment_scores',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('total_alignment_score', sa.Float(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_match_score', sa.Float(), nullable=True),
    sa.Column('cultural_fit_score', sa.Float(), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alignment_scores_created_at'), 'alignment_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_alignment_scores_id'), 'alignment_scores', ['id'], unique=False)
    op.create_index(op.f('ix_alignment_scores_is_deleted'), 'alignment_scores', ['is_deleted'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('changes_applied', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_created_at'), 'resume_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_resume_versions_id'), 'resume_versions', ['id'], unique=False)
    op.create_index(op.f('ix_resume_versions_is_deleted'), 'resume_versions', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_versions_is_deleted'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_created_at'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_alignment_scores_is_deleted'), table_name='alignment_scores')
    op.drop_index(op.f('ix_alignment_scores_id'), table_name='alignment_scores')
    op.drop_index(op.f('ix_alignment_scores_created_at'), table_name='alignment_scores')
    op.drop_table('alignment_scores')
    op.drop_index(op.f('ix_skill_gaps_is_deleted'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_created_at'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_resumes_is_deleted'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_learning_paths_is_deleted'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_created_at'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_job_descriptions_is_deleted'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_created_at'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_dashboard_snapshots_is_deleted'), table_name='dashboard_snapshots')
    op.drop_index(op.f('ix_dashboard_snapshots_id'), table_name='dashboard_snapshots')
    op.drop_index(op.f('ix_dashboard_snapshots_created_at'), table_name='dashboard_snapshots')
    op.drop_table('dashboard_snapshots')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
